Models/ViewModels/WeddingViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using WeddingPlanner.Models.CustomValidations;

namespace WeddingPlanner.Models
{
    public class WeddingViewModel : BaseEntity
    {
        [Required(ErrorMessage = "Name of bride/groom required")]
        [MinLength(2, ErrorMessage = "Name must be longer than 2 characters")]
        [Display(Name = "Wedder One: ")]
        public string WedderOne { get; set; }
        [Required(ErrorMessage = "Name of bride/groom required")]
        [MinLength(2, ErrorMessage = "Name must be longer than 2 characters")]
        [Display(Name = "Wedder Two: ")]

        public string WedderTwo { get; set; }
        
        [Display(Name = "Date of Wedding: ")]
        [Required(ErrorMessage = "Date required")]
        [DataType(DataType.Date)]
        [InTheFuture(ErrorMessage = "Date of event must be in the future.")]
        public DateTime? Date { get; set; }
        
        
        [Display(Name = "Address: ")]
        [Required(ErrorMessage = "Address required")]
        public string Address { get; set; }
    }
}

Models/Wedding.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using Microsoft.EntityFrameworkCore;

namespace WeddingPlanner.Models
{
    public class Wedding : BaseEntity
    {
        [Key]
        public int WeddingId { get; set; }
        public string WedderOne { get; set; }
        public string WedderTwo { get; set; }

        [FutureDate(ErrorMessage = "Wedding must be in the future!")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM-dd-yyyy}")]
        public DateTime Date { get; set; }
        public string Address { get; set; }
      
        [ForeignKey("User")]
        public int userId { get; set; }
        public User User {get; set;}

        public List<GuestList> Guests { get; set; }

        // instantiating the list; guest objects.  //
        public Wedding()
        {
            Guests = new List<GuestList>();
        }


        public class FutureDateAttribute : ValidationAttribute
        {
            public FutureDateAttribute() { }
            public override bool IsValid(object value)
            {
                var date = (DateTime)value;
                if (date > DateTime.Now)
                {
                    return true;
                }
                return false;
            }
        }
    }
}

Controllers/WeddingController.cs
using System;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WeddingPlanner.Models;
using System.Linq;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using System.Globalization;
using System.ComponentModel.DataAnnotations;

namespace WeddingPlanner
{
    public class WeddingController : Controller
    {
         public bool ErrorMessage { get; private set; }
        private WeddingPlannerContext _context;
        public WeddingController(WeddingPlannerContext context)
        {
            _context = context;
        }
            [HttpGet , Route("Dashboard")]
            public IActionResult Dashboard()
            {
                System.Console.WriteLine("In Dashboard about to get username");
               
                var AreTheyLoggedIn = IsLoggedIn();
                if (AreTheyLoggedIn == true)
                {
                    int? LoginId = HttpContext.Session.GetInt32("CurrentUser");
                    if ((int)LoginId != 0)
                    {
                        User thisUser = GetUserInfo();
                        List<Wedding> AllWeddings = _context.weddings.Include(a => a.Guests).ToList();
                        ViewBag.UserInfo = thisUser;
                        ViewBag.userId = thisUser.userId;
                        ViewBag.AllWeddings = AllWeddings;

                    // ************************* */*********************************8//
                    foreach(var wedding in ViewBag.AllWeddings)
                    {
                        System.Console.WriteLine(wedding.Guests.Count);
                       
                            if(wedding.userId == ViewBag.userId)
                    {
                       System.Console.WriteLine("CHECK ONE");
                    }
                    else
                    {
                            bool attending = false;
                            foreach(var guest in wedding.Guests)
                        {
                                if(guest.userId == ViewBag.userId)
                            {
                                    attending = true;
                                    break;
                                }
                            }

                            if(attending)
                    {
                       System.Console.WriteLine(" CHECK TWO");
                    }
                    else
                    {
                       System.Console.WriteLine(" CHECK THREE");
                    }
                        }
        }

// ***********************************8//
                        User ConfirmedUser = GetUserInfo();
                    }
                    return View("Dashboard");
                }
                return RedirectToAction("Index", "LogReg");
            }


            [HttpPost, Route("addWedding")]
            public IActionResult addWedding(WeddingViewModel WeddingSignUp)
            {
                
                System.Console.WriteLine("****************Creating Wedding Man!!!!**************");

               

                TryValidateModel(WeddingSignUp);
        
                    if(ModelState.IsValid)
                    {
                    User UserInfo = GetUserInfo();
                     int? CurrentUserId = HttpContext.Session.GetInt32("CurrentUser");
                 
                        Wedding newWedding = new Wedding
                        {
                            WedderOne = WeddingSignUp.WedderOne,
                            WedderTwo = WeddingSignUp.WedderTwo,
                            Date = (DateTime)WeddingSignUp.Date,
                            Address = WeddingSignUp.Address,
                            userId = UserInfo.userId,
                            CreatedAt = DateTime.Now,
                            UpdatedAt = DateTime.Now
                        };
                        _context.Add(newWedding);
                        _context.SaveChanges();
                        HttpContext.Session.SetInt32("CurrentWedding", newWedding.WeddingId);
                        GetWeddingInfo();
                        return RedirectToAction("ViewWedding", new { id = newWedding.WeddingId});
                    }
                    else
                    {
                        System.Console.WriteLine("ERROR: Wedding NOT Created, Fail");
                        TempData["Message"] = "Something is invalid here..";
                        return View("NewWedding");
                    }
                }
    

            [HttpGet, Route("ANewWedding")]

            public IActionResult ANewWedding()
            {
                return View("NewWedding");
            }


            [HttpGet]
            [Route("ViewWedding/{id}")]
        public IActionResult ViewWedding(int id)
        {
            // Grab your guest then singleout the wedding///
            List<Wedding> viewableWedding = _context.weddings.Where(w => w.WeddingId == id).Include(w => w.Guests).ThenInclude(u => u.User).ToList();
            if(viewableWedding.Count == 1 ){
                System.Console.WriteLine("List of Guess for Wedding.");
                ViewBag.WeddingInfo = viewableWedding[0];
            }
            return View("ViewWedding");
        }


        private User GetUserInfo()
            {
                int? LoginId = HttpContext.Session.GetInt32("CurrentUser");
                if ((int)LoginId != 0)
                {
                    User ConfirmedUser = _context.users.SingleOrDefault(User => User.userId == LoginId);
                    @ViewBag.UserInfo = ConfirmedUser;
                    return ConfirmedUser;

                }
                else
                {
                    return null;
                }
            }

            private Wedding GetWeddingInfo()
            {
                int? WeddingId = HttpContext.Session.GetInt32("CurrentWedding");
                if((int)WeddingId != 0)
                {
                    Wedding ConfirmedWedding = _context.weddings.SingleOrDefault( Wedding => Wedding.WeddingId == WeddingId);
                    @ViewBag.WeddingInfo = ConfirmedWedding;
                    return ConfirmedWedding;
                }
                else 
                {
                    return null;
                }
            }

            public bool IsLoggedIn()
            {
                if (HttpContext.Session.GetInt32("CurrentUser") == null)
                {
                    // 1)do nothing but convert null to zero to home page. 
                    @ViewBag.LoggedIn = false;
                    HttpContext.Session.SetInt32("CurrentUser", 0);
                    return false;
                }
                // 2) is there user id in session and using it
                else if (HttpContext.Session.GetInt32("CurrentUser") > 0)
                {
                    @ViewBag.LoggedIn = true;
                    return true;
                }
                // 3) catch weird scenarios and let you know that you're not logged in //
                else
                {
                    @ViewBag.LoggedIn = false;
                    return false;
                }
            }

        [HttpGet, Route("Delete/{id}")]
        public IActionResult Delete(int id)
        {
            Wedding RemoveWedding = _context.weddings.SingleOrDefault(wed => wed.WeddingId == id);
            _context.weddings.Remove(RemoveWedding);
            _context.SaveChanges();
            Console.WriteLine("********* Wedding Deleted *********");
            return RedirectToAction("Dashboard");
        }
        
        [HttpGet, Route("RSVP/{id}")]
        public IActionResult RSVP(int id)
        {
            System.Console.WriteLine("*******  ADDING RSVP *******");
            int? CurrentUserId = HttpContext.Session.GetInt32("CurrentUser");

            GuestList AttendingGuest = new GuestList
            {
                WeddingId= id,
                userId = (int)CurrentUserId
            };
            System.Console.WriteLine("******* About to add Guest to Wedding *********");
            _context.GuestList.Add(AttendingGuest);
            _context.SaveChanges();


            System.Console.WriteLine("******* About to add Guest to Wedding *********");
            System.Console.WriteLine(AttendingGuest);
            System.Console.WriteLine("******* Guest HAS BEEN ADDED TO THE GuestList *********");

            return RedirectToAction("Dashboard");
        }
       
        [HttpGet, Route("unRSVP/{id}")]
        public IActionResult unRSVP(int id)
        {
            int? CurrentUserId = HttpContext.Session.GetInt32("CurrentUser");
            GuestList RemoveUser = _context.GuestList.Where(a => a.WeddingId == id && a.userId == CurrentUserId).SingleOrDefault( c => c.WeddingId == id);
            
            _context.GuestList.Remove(RemoveUser);
            _context.SaveChanges();
            Console.WriteLine("********* You Un-RSVPed *********");
            return RedirectToAction("Dashboard");
        }

        
    }
}

Views/Wedding/Dashboard.cshtml
@model WeddingPlanner.Models.WeddingViewModel;
@using WeddingPlanner.Models; 

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>Welcome to the Wedding Planner, @ViewBag.UserInfo.FirstName !</h1>
    <a href="/ANewWedding" ><button class="btn btn-primary">New Wedding</button></a>
     <!-- <a href="/Logout" ><button class="btn btn-primary">Logout</button></a> -->
     <hr>
<table  class="table table-hover table-dark">
     <thead>
            <th class="col-sm-4">Wedding</th>
            <th class="col-sm-5">Date</th>
            <th class="col-sm-2">Guest</th>
            <th class="col-sm-5">Action</th>
        </thead>
    <tbody>
      @foreach(var wedding in ViewBag.AllWeddings)
        {
            <tr>
                <td><a href="/ViewWedding/@wedding.WeddingId">@wedding.WedderOne &amp; @wedding.WedderTwo</a></td>
                <td>@wedding.Date.ToString("MMM d, yyyy")</td>
                <td>@wedding.Guests.Count</td>
                <td>
                @if(wedding.userId == ViewBag.userId)
                    {
                        <td><a asp-action="Delete" asp-controller="Wedding" asp-route-id="@wedding.WeddingId">Delete</a></td>
                    }
                    else
                    {
                        bool attending = false;
                        @foreach(var guest in wedding.Guests)
                        {
                            @if(@guest.userId == ViewBag.userId)
                            {
                                attending = true;
                                break;
                            }
            
                    }
                    @if(attending)
                    {
                        <a asp-action="unRSVP" asp-route-id="@wedding.WeddingId">un-RSVP</a>
                    }
                    else
                    {
                        <a asp-action="RSVP" asp-route-id="@wedding.WeddingId">RSVP</a>
                    }
                }
                </td>
            </tr>
        }
  </tbody>
  </table>
</body>

Views/Wedding/NewWedding.cshtml
@model WeddingPlanner.Models.WeddingViewModel;
@using WeddingPlanner.Models; 


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>Plan Your Wedding</h1>
    <a href="/Dashboard" ><button class="btn btn-info">Dashboard</button></a>
    <a href="/Logout" ><button class="btn btn-info">Logout</button></a>
    <hr>
<div>
    <form asp-controller="Wedding" asp-action="addWedding" class="form-horizontal" method="POST" >
        <!-- <span asp-validation-for="IsValid"></span> -->
        <div class="form-group">
            <span asp-validation-for="WedderOne"></span>
            <label asp-for="WedderOne" class="col-sm-2 control-label">Wedder One</label>
            <div class="col-sm-3">
             <input asp-for="WedderOne" class="form-control" placeholder="WedderOne"/>
            </div>
        </div>
        
        <div class="form-group">
            <span asp-validation-for="WedderTwo"></span>
            <label asp-for="WedderTwo" class="col-sm-2 control-label">Wedder Two</label>
            <div class="col-sm-3">
                <input asp-for="WedderTwo" class="form-control" placeholder="WedderTwo"/>
            </div>
        </div>
         <div class="form-group">
            <div class="input-append date form_datetime" data-date="2018-04-23T15:25:00Z">
                <label asp-for="Date" class="col-sm-2 control-label">Date</label>
            <div class="col-sm-3">
                <input asp-for="Date" id="date" type="date" name="Date">
                <span class="add-on"><i class="icon-remove"></i></span>
                <span class="add-on"><i class="icon-calendar"></i></span>
                @TempData["futuredate"]
                @ViewBag.ErrorMessage
            <!-- <span>@TempData["message"]</span> -->
            </div>
            </div>
        </div>

        <div class="form-group">
            <span asp-validation-for="Address"></span>        
            <label asp-for="Address" class="col-sm-2 control-label">Address</label>
            <div class="col-sm-3">
                <input asp-for="Address" class="form-control"  placeholder="Address" name="Address">
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
            <input type="submit" value="Create" class="btn btn-primary">
            </div>
        </div>
    </form>
    
</body>
</html>

Views/Wedding/ViewWedding.cshtml
@model WeddingPlanner.Models.WeddingViewModel;
@using WeddingPlanner.Models;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>

<body>

 <h1 class='text-info'> @ViewBag.WeddingInfo.WedderOne &AMP; @ViewBag.WeddingInfo.WedderTwo 's Wedding </h1>

    <a href="/Dashboard" ><button class="btn btn-info">Dashboard</button></a>
    <a href="/Logout" ><button class="btn btn-info">Logout</button></a>
    <h3>Date: @ViewBag.WeddingInfo.Date </h3>


    <h3>Guests:</h3>
        <!-- // if currect user is on list do not include -->
    @foreach( var guest in @ViewBag.WeddingInfo.Guests)
    {
        <ul>
                <li> @guest.User.FirstName @guest.User.LastName</li>                    
          </ul>  
        
    }
    


<br>
<div ></div>
<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d43040.117894844356!2d-122.19887410000001!3d47.60654640000001!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sus!4v1524620354806" width="400" height="250" frameborder="0" style="border:5px" allowfullscreen></iframe>
</body>
</html>